version: '3.9'
services:
  nodejs:
    container_name: nodejs
    image: node:18
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/nodejs
    working_dir: /nodejs
    tty: true
